# Additional Array Properties

- `itemsize` 
- `nbytes` 
- `T`  (transpose)
- `strides` 
- `flags`

> These properties describe **memory layout and data movement**, not just shape.

### ***Syntax & Examples***
We use two different array and inspect all properties

In [2]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)

In [6]:
x = np.array([1.5, 2.5])

# 1. `itemsize`

In [8]:
arr.itemsize

4

Explanation:
- int32 = 4 bytes
- Each element uses 4 bytes

In [9]:
x.itemsize

8

Explanation:
- float64
- Higher precision, more memory

# 2. `nbytes`

In [10]:
arr.nbytes

24

Explanation:
- 6 elements
- 6 × 4 bytes = 24

In [11]:
x.nbytes

16

Explanation:
- 2 × 8 bytes

# 3. `T`(Transpose)

In [12]:
# original arrays 

print(arr)
print(x)

[[1 2 3]
 [4 5 6]]
[1.5 2.5]


In [18]:
# Transpose

print(arr.T)
print(arr.shape)
print(arr.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


Explanation:
- Shape changed from (2,3) to (3,2)
- Data not copied

In [15]:
print(x.T)

[1.5 2.5]


# 4. `strides` 

In [19]:
print(arr.strides)

(12, 4)


Explanation:
- Move 12 bytes to next row
- Move 4 bytes to next column
 

# 5.`flags`

In [20]:
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Explanation:

- Stored row-wise
- Can be modified
- Owns its memory