# 3. Array Properties

- `shape`
- `ndim`
- `size` 
- `dtype`

> **Array Properties** describe the basic facts about a NumPy array.
They tell you **what the array looks like in memory.**

### ***Syntax & Examples***
We use two different array and inspect all properties.

In [2]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], 
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x = np.array([10,20,30,40])
x

array([10, 20, 30, 40])

## 1. `shape`

In [4]:
arr.shape

(2, 3)

Explanation:
- 2 rows
- 3 columns
- Tuple format

In [5]:
x.shape

(4,)

Explanation:
- 1D array
- Single dimension
- Trailing comma means tuple

## 2. `ndim`

In [6]:
arr.ndim

2

Explanation:
- 2 axes
- Row axis + column axis

In [7]:
x.ndim

1

Explanation:
- Single axis
- Flat vector

## 3. `size`

In [8]:
arr.size

6

Explanation:
- 2 × 3 = 6 elements

In [9]:
x.size

4

Explanation:
- Total count
- Independent of shape style

## 4. `dtype`

In [10]:
arr.dtype

dtype('int64')

In [11]:
x.dtype

dtype('int64')

Explanation:
- 64-bit integer
- Fixed memory per element


In [12]:
y = np.array([1.2,3.2,4.2])
y

array([1.2, 3.2, 4.2])

In [13]:
y.dtype

dtype('float64')

Explanation:
- Decimal numbers
- More memory than int

## Practice Problems

**Easy (5)**
1. Create a 1D array of 10 integers. Print all properties.
2. Convert a list of floats to array. Check dtype.
3. Create a 3×4 array. Print size.
4. Create a single value array. Check ndim.
5. Compare shape of  [1,2,3]  and  [[1,2,3]] .

In [17]:
# 1. Create a 1D array of 10 integers. Print all properties.

arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)

print(f'shape: {arr.shape}')
print(f'ndim: {arr.ndim}')
print(f'size: {arr.size}')
print(f'dtype: {arr.dtype}')

[ 10  20  30  40  50  60  70  80  90 100]
shape: (10,)
ndim: 1
size: 10
dtype: int64


In [34]:
# 2. Convert a list of floats to array. Check dtype.
list = [10.1,20.2,30.3,40.4,50.5]
arr = np.array(list)
print(arr)
arr.dtype
arr.shape

[10.1 20.2 30.3 40.4 50.5]


(5,)

In [24]:
# 3. Create a 3×4 array. Print size.

arr = np.array([[10,20,30,40],
               [50,60,70,80], 
               [90,100,110,120]
               ])
print(arr)
arr.size

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


12

In [35]:
# 4. Create a single value array. Check ndim.

arr = np.array([101])
arr.ndim

1

In [30]:
# 5. Compare shape of [1,2,3] and [[1,2,3]] .

x = np.array([1,2,3])
y = np.array([[1,2,3]])
print(x)
print(y)
print(x.shape)
print(y.shape)

[1 2 3]
[[1 2 3]]
(3,)
(1, 3)


Before starting other example let's: 

**How to Loading CSV Numeric Data in NumPy?**

***Method 1: `np.loadtxt()`(Strict)***

Use when:

- File is clean
- No missing values
- All numeric

In [38]:
data = np.loadtxt("data.csv",delimiter=',')
print(data)
print("Shape:", data.shape)
print("ndim:", data.ndim)
print("dtype:", data.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Shape: (3, 3)
ndim: 2
dtype: float64


Explanation:

- 3 rows
- 3 columns
- Default dtype is float64
- Always 2D if multiple rows

***Method 2: `np.genfromtxt()` (Flexible)***

Use when:

- Missing values exist
- Mixed formatting
- Need more control

In [50]:
data = np.genfromtxt("missingdata.csv",delimiter=",")
print(data)
print(data.shape)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
(3, 3)


In [49]:
data = np.genfromtxt("missingdata.csv", delimiter=",", filling_values=0)
print(data)
print(data.shape)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]
(3, 3)


Explanation:

- Missing value replaced with 0
- Shape remains consistent

In [52]:
# CSV data with hearder
# Used when first row contains column names.

data = np.loadtxt("datawithheader.csv",delimiter=",",skiprows=1)
print(data)

[[ 25. 170.  70.]
 [ 30. 165.  65.]]


**Medium (7)**
1. Load CSV numeric data into array. Validate shape.
2. Check if feature matrix is 2D before training.
3. Detect wrong dtype after division.
4. Reshape array and verify size unchanged.
5. Identify samples vs features using shape.
6. Convert int array to float for ML.

In [54]:
# 1. Load CSV numeric data into array. Validate shape.

data = np.loadtxt("data.csv",delimiter=",")
print(data)
print(data.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)


In [7]:
# 2. Check if feature matrix is 2D before training.
matrix = np.array([1,2,3])

if matrix.ndim != 2:
    raise ValueError("Feature matrix must be 2D")

ValueError: Feature matrix must be 2D

In [60]:
# 3. Detect wrong dtype after division.
x = np.array([1,2,3],dtype = np.int32)
y = x / 2
print(y)
print(f"dtype: {y.dtype}")

[0.5 1.  1.5]
dtype: float64


In [17]:
# 4. Reshape array and verify size unchanged.

arr = np.arange(1,101)
print(f"Before reshape:{arr.size}")
re = arr.reshape(2,2,5,5)
print(re)
print(f"After reshape:{re.size}")
re.shape

Before reshape:100
[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]
   [ 21  22  23  24  25]]

  [[ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]
   [ 41  42  43  44  45]
   [ 46  47  48  49  50]]]


 [[[ 51  52  53  54  55]
   [ 56  57  58  59  60]
   [ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]]

  [[ 76  77  78  79  80]
   [ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]]]
After reshape:100


(2, 2, 5, 5)

In [24]:
# 5. Identify samples vs features using shape.

data = np.array([[1,2,3,4],
                [6,7,8,9],
                [10,11,12,13]])
print(data.shape)
print(data)
# 3 samples, 4 features 

(3, 4)
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]


In [6]:
# 6. Convert int array to float for ML.
arr = np.array([[1,2,3,4],
               [4,3,2,1]],
               dtype = np.float32)
arr.dtype

dtype('float32')

**Hard (5)**
1. Validate input for linear regression model.
2. Detect memory waste due to wrong dtype.
3. Ensure batch input shape for neural network.
4. Debug silent model failure using shape logs.
5. Compare performance using int32 vs float64.
