#  Indexing & Slicing

> Indexing and slicing mean **selecting parts of a NumPy array**.

- **1D Indexing**
- **2D Indexing [row, column]**
- **Row Slicing**
- **Column Slicing**
- **Step Slicing**
- **Negative Indexing**

### ***Syntax & Examples***

## 1D Indexing

***syntax***
```python
arr[index]
````

***Example 1***

In [1]:
import numpy as np

In [2]:
arr = np.array([12,20,32,43,56])
print(arr[2])

32


Explanation
- Index 2 → third element
- Indexing starts from 0

***Example 2***

In [3]:
print(arr[-1])

56


Explanation

- -1  → last element

## 2D Indexing [row, column]
***Syntax***
```python 
arr[row, col]
```
***Example 1***

In [6]:
matrix = np.array([[12,54,67,98],
                   [32,65,78,90],
                   [56,77,33,22]])
print(matrix[1][2])

78


Explanation
- Row index 1 → second row
- Column index 2 → third column

***Example 2***

In [8]:
print(matrix[0][0])

12


## Row Slicing
***Syntax***
```python
arr[start_row:stop_row, :]
```
***Example 1***

In [96]:
matrix = np.array([[1,2,3],
                  [4,5,6], 
                  [7,8,9],
                  [10,11,12]])

print(matrix[0:2,:])

[[1 2 3]
 [4 5 6]]


Explanation
- Rows 0 and 1 selected
- `,:`  means all columns

In [98]:
matrix = np.arange(1,101)
matrix = matrix.reshape(10,10)
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [100]:
print(matrix[7:9,:])

[[71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]]


## Column Slicing
***Syntax***
```python
arr[:, start_col:stop_col]
```
***Example***

use same array 

In [105]:
print(matrix[:,5:10])

[[  6   7   8   9  10]
 [ 16  17  18  19  20]
 [ 26  27  28  29  30]
 [ 36  37  38  39  40]
 [ 46  47  48  49  50]
 [ 56  57  58  59  60]
 [ 66  67  68  69  70]
 [ 76  77  78  79  80]
 [ 86  87  88  89  90]
 [ 96  97  98  99 100]]


In [106]:
print(matrix[:,0:5])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]
 [61 62 63 64 65]
 [71 72 73 74 75]
 [81 82 83 84 85]
 [91 92 93 94 95]]


## Step Slicing(row)
***Syntax***
```python
arr[start:stop:step,:]
```
***Example***

In [126]:
print(matrix[1:10:2,:])

[[ 11  12  13  14  15  16  17  18  19  20]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 91  92  93  94  95  96  97  98  99 100]]


## Step Slicing(column)
***Syntax***
```python
arr[:,start:stop:step]
```
***Example***

In [128]:
print(matrix[:,1:10:2])

[[  2   4   6   8  10]
 [ 12  14  16  18  20]
 [ 22  24  26  28  30]
 [ 32  34  36  38  40]
 [ 42  44  46  48  50]
 [ 52  54  56  58  60]
 [ 62  64  66  68  70]
 [ 72  74  76  78  80]
 [ 82  84  86  88  90]
 [ 92  94  96  98 100]]


## Step Slicing
***Syntax***
```python
arr[start:stop:step]
```
***Example***

In [129]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[0:10:2])

[0 2 4 6 8]


Explanation
- Step = 2
- Every second element


## Negative Indexing
***Syntax***
```python
arr[-1,:]
```
***Example***

In [131]:
print(matrix[-1,:])

[ 91  92  93  94  95  96  97  98  99 100]
