# Practice Problems
### Easy (5)

1. Select the 3rd element from a 1D array
2. Get last element using negative indexing
3. Select first row from 2D array
4. Select second column from matrix
5. Slice first 5 elements from array

---

### Medium (7)

6. Select rows 2 to 5 from dataset matrix
7. Extract feature columns except target
8. Select every alternate value from signal data
9. Get last 3 rows from time-series array
10. Select middle column from odd-column matrix
11. Slice training data using index range
12. Remove first column from feature matrix

---

### Hard (5)

13. Create sliding window using slicing
14. Extract diagonal block from matrix
15. Split dataset into X and y using indexing
16. Batch data using step slicing
17. Reverse array using slicing

---

### Industry-Level Tasks (3)

18. Select last 30 days from stock price matrix
19. Extract sensor channels from IoT data array
20. Prepare mini-batches for neural network input

---

In [3]:
import numpy as np

***1. Select the 3rd element from a 1D array***

In [8]:
arr = np.arange(21,80)
print(arr)
print(f"3rd element:{arr[2]}")

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77 78 79]
3rd element:23


***2. Get last element using negative indexing***


In [11]:
arr = np.arange(41,71)
print(arr[-1])

70


***3. Select first row from 2D array***

In [50]:
mat = np.arange(1,26)
mat = mat.reshape(5,5)
print(f"Matrix:{mat}\n")
print(f"First Row: {mat[0:1]}")

Matrix:[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row: [[1 2 3 4 5]]



***4. Select second column from matrix***

In [52]:
# use same matrix

print(mat[:,1:2])

[[ 2]
 [ 7]
 [12]
 [17]
 [22]]



***5. Slice first 5 elements from array***

In [36]:
arr = np.arange(1,21)
print(f"Full Array: {arr}")
print(f"Fisrt 5 Elements: {arr[:5]}")

Full Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Fisrt 5 Elements: [1 2 3 4 5]


***6. Select rows 2 to 5 from dataset matrix***


***7. Extract feature columns except target***


***8. Select every alternate value from signal data***


***9. Get last 3 rows from time-series array***


***10. Select middle column from odd-column matrix***


***11. Slice training data using index range***


***12. Remove first column from feature matrix***

***13. Create sliding window using slicing***


***14. Extract diagonal block from matrix***


***15. Split dataset into X and y using indexing***


***16. Batch data using step slicing***


***17. Reverse array using slicing***

***18. Select last 30 days from stock price matrix***


***19. Extract sensor channels from IoT data array***


***20. Prepare mini-batches for neural network input***