# 1. `np.array()`

Creates a NumPy array from existing data like lists or tuples.

In [5]:
import numpy as np

In [22]:
# 1D
list = [1,2,3,4,5]
array = np.array(list)
print(array)
print(array.ndim)

[1 2 3 4 5]
1


In [20]:
# 2D

array = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
        ])
print(array)
print(array.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [37]:
#3D(1,3,4)
array = np.array([[
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
            ]])
array
# array.shape
# array.reshape(2,3,4) // ValueError: cannot reshape array of size 12 into shape (2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [13]:
# 3D (1,6,4)
array = np.array([[
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [10,20,30,40],
            [50,60,70,80],
            [90,100,110,120]
            ]])
print(array)
array.shape

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


(1, 6, 4)

In [25]:
# 3D (2,3,4)
array = np.array([[
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [10,20,30,40],
            [50,60,70,80],
            [90,100,110,120]
            ]])
a = array.reshape(2,3,4)
print(a)
a.shape

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


(2, 3, 4)

### Problem 1: List to 1D Array

You are given numeric data as a Python list.

```python
data = [10, 20, 30, 40]
```

**Task:**
Create a NumPy array using `np.array()` and print its shape.



In [47]:
x = np.array([10, 20, 30, 40])
print(x)
print(x.shape)
# Shape (n,) means 1D array

[10 20 30 40]
(4,)



### Problem 2: List of Lists to 2D Array

You receive tabular data as a list of lists.

```python
records = [
    [1, 2],
    [3, 4],
    [5, 6]
]
```

**Task:**
Convert this into a NumPy array using `np.array()` and verify the number of rows and columns.


In [41]:
records = [
    [1, 2],
    [3, 4],
    [5, 6]
]

x = np.array(records)
print(x)
print(x.shape)
# This is a valid feature matrix (X) with shape (n_samples, n_features).

[[1 2]
 [3 4]
 [5 6]]
(3, 2)



### Problem 3: Tuple to NumPy Array

Data comes from a function as a tuple.

```python
coords = (5, 10, 15)
```

**Task:**
Create a NumPy array using `np.array()` and check whether it is 1D or 2D.


In [45]:
coords = (5, 10, 15)
x = np.array(coords)
print(x)
print(x.shape)
# Shape (n,) means 1D array

[ 5 10 15]
(3,)



### Problem 4: Detecting dtype Conversion

A mixed-type list is passed to `np.array()`.

```python
values = [100, 200.5, 300]
```

**Task:**
Convert it using `np.array()` and identify the resulting dtype.


In [44]:
values = [100, 200.5, 300]
x = np.array(values)
print(x)
print(x.dtype)

[100.  200.5 300. ]
float64



### Problem 5: Shape Bug Identification

A model expects input shape `(n_samples, n_features)`.

```python
X = np.array([7, 14, 21])
```

**Task:**
Explain why this shape is incorrect for ML input and how `np.array()` should be used to create the correct shape.


In [50]:
x = np.array([7, 14, 21])
print(x.shape)
y = x.reshape(1,3)
print(y.shape)

(3,)
(1, 3)


The array

```python
X = np.array([7, 14, 21])
```

has shape **`(3,)`**, which is a **1D array**.
ML models expect a **2D array** of shape `(n_samples, n_features)`, so this breaks matrix operations.

To fix it, `np.array()` must be used to create a **2D array** with the intended meaning:

* **3 samples, 1 feature**

```python
X = np.array([[7], [14], [21]])   # shape (3, 1)
```

* **1 sample, 3 features**

```python
X = np.array([[7, 14, 21]])       # shape (1, 3)
```

The correct shape depends on whether the values represent **multiple samples** or **multiple features**.

**Key point:**

> A 1D array `(n,)` is not valid ML input; data must be explicitly shaped as `(n_samples, n_features)`.
