# 2. `np.zeros()`

Creates an array filled with 0s.



In [1]:
import numpy as np

In [4]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
x.shape

(3, 4)

In [6]:
x.dtype

dtype('float64')

In [7]:
x.ndim

2

In [8]:
x.size

12

In [21]:
# ML usage
weights = np.zeros((5,))
# Used when you want predictable starting values.

weights

array([0., 0., 0., 0., 0.])

### Problem 1: Weight Initialization

You are building a linear model with **4 input features**.

**Task:**
Create a NumPy array for model weights using `np.zeros()`.


In [22]:
x = np.zeros((4,))
print(x)

[0. 0. 0. 0.]



### Problem 2: Placeholder Output Array

A prediction pipeline will generate **100 outputs**, but values will be filled later.

**Task:**
Create a placeholder array using `np.zeros()` with the correct shape.


In [26]:
x = np.zeros(100,)
print(x)
x.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


(100,)


### Problem 3: Accumulator for Loss Tracking

You train a model for **10 epochs** and want to store total loss per epoch.

**Task:**
Create an accumulator array using `np.zeros()`.


In [27]:
x = np.zeros(10,)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


### Problem 4: Mask Creation

You have **6 data samples** and want a mask array initialized to zero.

**Task:**
Create the mask using `np.zeros()` with an integer dtype.


In [32]:
x = np.zeros((6,),dtype=int)
print(x)

[0 0 0 0 0 0]


### Problem 5: Shape Debugging

A developer writes:

```python
arr = np.zeros(5)
```

**Task:**
Explain why this is incorrect usage and how `np.zeros()` should be called properly.


👉 **`arr = np.zeros(5)` is NOT incorrect by itself.**
It is only incorrect **in context**.

The problem is testing whether you understand **when this line is wrong**, not whether the syntax is valid.

---

### Why `np.zeros(5)` is technically correct

This line creates:

* a **1D array**
* with **5 elements**
* shape = `(5,)`

So if the developer wanted:

* a vector
* a list of 5 values
* weights for 5 features
* a mask for 5 samples

Then this line is **perfectly fine**.

---

### Why it can be incorrect usage (this is the real point)

It becomes **incorrect** when the **intended shape was 2D**, but the developer accidentally created 1D.

Common cases where this line is wrong:

* The model expects shape `(5, 1)` but got `(5,)`
* The code later treats `arr` like a matrix (rows and columns)
* Broadcasting or dot products behave unexpectedly
* Indexing like `arr[i][0]` fails

The mistake is **not using `np.zeros`**,
the mistake is **not specifying the intended shape**.

---

### How `np.zeros()` should be called properly

`np.zeros()` should be called in a way that **matches the meaning of the data**.

* If you want **one value per item** → 1D shape
* If you want **rows and columns** → 2D shape must be explicit

The correct usage is:

* Be explicit when dimensions matter
* Use a tuple when more than one dimension exists

In short:

> The bug is not syntax.
> The bug is **shape mismatch between intention and implementation**.

---

### Brutally honest takeaway

Most NumPy bugs are not crashes.
They are **quiet shape mistakes** that give wrong results.

If a developer can’t explain **why `(5,)` vs `(5,1)` matters**, they don’t understand NumPy yet.

You’re learning to spot that. That’s the real win here.
