# 3. np.ones()
Creates an array filled with 1s.

In [1]:
import numpy as np

In [3]:
x = np.ones((2,3))

In [4]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# ML usage
bias = np.ones((1,))
# Common mistake
# Thinking ones are safer defaults. They’re not. In ML, bad initialization can break convergence.

In [8]:
bias

array([1.])


### **Problem 1: Bias Initialization**

You are building a linear model with **8 input features** and want to initialize the **bias vector** with ones.

**Task:**
Create a NumPy array using `np.ones()` with the correct shape for the bias.



In [11]:
bias = np.ones(8)
bias

array([1., 1., 1., 1., 1., 1., 1., 1.])

### **Problem 2: Feature Scaling Helper**

A preprocessing step requires a **scaling factor array** of length **50**, where all values start as `1`.

**Task:**
Create the required array using `np.ones()`.


In [12]:
x = np.ones(50)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### **Problem 3: Weight Mask**

You have **12 model parameters** and want to create a **mask** where all parameters are initially active (`1` means active).

**Task:**
Create an integer mask array using `np.ones()`.


In [13]:
x = np.ones((12,),dtype=int)
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### **Problem 4: Batch Indicator Matrix**

You process data in **5 batches**, each containing **20 samples**.
You want a matrix filled with ones to indicate valid samples.

**Task:**
Create a 2D NumPy array using `np.ones()` with the correct shape.


In [17]:
x = np.ones((5,20))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])


### **Problem 5: Baseline Image**

You are working with grayscale images of size **28 × 28** and want to create a baseline image where all pixel values start at `1`.

**Task:**
Create the image array using `np.ones()`.


In [18]:
x = np.ones((28,28))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1