# 4. `np.empty()`
Creates an array without initializing values.

In [1]:
import numpy as np

In [4]:
x = np.empty((3,3))

In [5]:
x

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 9.27e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

array([0., 0., 0., ..., 0., 0., 0.], shape=(10000000,))

### **Problem 1: Preallocated Prediction Buffer**

A model will generate **500 predictions** during evaluation, and values will be written directly without needing initialization.

**Task:**
Create an array using `np.empty()` with the correct shape.


In [10]:
x = np.empty((500,))
x

array([6.79438062e-312, 6.79437372e-312, 6.79618541e-312,             nan,
       0.00000000e+000, 0.00000000e+000, 6.79618541e-312, 6.79618541e-312,
       9.89803212e+164, 0.00000000e+000, 3.95252517e-323, 1.42137819e-076,
       9.48698916e+217, 8.71280277e+183, 1.42137849e-076, 9.37081843e-076,
       1.12576162e-153, 6.98684252e-077, 1.76539223e+137, 1.43573466e-023,
       5.36835869e+252, 9.89803615e+164, 6.01347002e-154, 1.39804329e-076,
       9.16281387e-072, 1.85027473e+031, 1.42137849e-076, 6.01390853e-154,
       1.91820845e+136, 1.10136572e-152, 8.27137249e+136, 4.65248269e+199,
       1.67850121e+243, 8.25573883e+136, 9.54775502e+213, 5.29372284e+180,
       3.03181047e+180, 9.10016856e+276, 5.82659539e+252, 1.76541730e+137,
       1.43573466e-023, 8.88420798e+252, 2.95153375e-075, 6.12572883e-154,
       2.59345489e+161, 8.02963163e-095, 3.12269278e+184, 2.72157670e+257,
       9.05293028e+223, 5.03128776e+180, 6.12743486e-154, 8.76372922e+252,
       1.43274574e+228, 2

### **Problem 2: Batch Feature Container**

You process **32 samples per batch**, each sample having **10 features**.
Memory should be allocated first, and values will be filled later.

**Task:**
Create the required array using `np.empty()`.


In [13]:
x = np.empty((32,10))
x

array([[6.79438148e-312, 6.79434609e-312, 6.79618541e-312,
                    nan, 0.00000000e+000, 0.00000000e+000,
        6.79618541e-312, 6.79618541e-312, 1.91914658e+136,
        0.00000000e+000],
       [3.95252517e-323, 2.00008875e+174, 5.38214630e+228,
        2.65141183e+180, 8.81430339e-106, 2.51719506e+180,
        6.80595212e+212, 3.94655078e+180, 4.88510887e+252,
        3.90657207e+180],
       [3.02876088e-152, 6.20651817e+223, 7.20364233e+159,
        8.02976905e-095, 9.82208445e+252, 1.17234088e+214,
        6.10936339e+223, 4.07474193e+223, 3.80985847e+180,
        4.51500037e-091],
       [4.47593816e-091, 1.27919412e-152, 1.66043036e+243,
        1.94209101e+227, 1.81155051e-152, 4.24819575e+180,
        1.27734658e-152, 9.13616837e+242, 1.05800998e+189,
        8.50085711e-096],
       [1.66041404e+243, 1.10393966e+136, 1.03474869e-028,
        1.11773383e+277, 9.77824555e+199, 6.12743629e-154,
        4.77503353e+180, 9.82395831e+252, 1.11773383e+277,
        2.3

### **Problem 3: Epoch-wise Metric Storage**

You train a model for **20 epochs** and want to store **two metrics (loss and accuracy)** per epoch.

**Task:**
Create an array using `np.empty()` with the correct shape.


In [20]:
x = np.empty((20,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])


### **Problem 4: Temporary Image Buffer**

You load a **single RGB image** of size **64 × 64** and want a temporary buffer before preprocessing.

**Task:**
Create the buffer using `np.empty()` with the correct shape.


In [23]:
x = np.empty((64,64,3))
x

array([[[6.79438359e-312, 6.79442582e-312, 1.81129406e-319],
        [            nan, 3.16251369e+180, 7.89353494e+165],
        [1.91077943e+214, 1.30343206e-142, 1.49004928e+195],
        ...,
        [9.30362224e+199, 9.44872517e-143, 1.14156319e+243],
        [6.99177865e+228, 2.66360353e+233, 7.45367790e+247],
        [9.25061154e+242, 2.59027909e-144, 4.31996535e-096]],

       [[1.28625721e+248, 6.87311563e+228, 4.50715929e+087],
        [2.85340351e+242, 4.50715929e+087, 8.22324143e+160],
        [1.04917936e-153, 2.59027921e-144, 9.45875071e-143],
        ...,
        [3.28710422e+161, 9.28485452e+159, 7.28395912e-143],
        [7.75444640e+228, 1.04917707e-153, 2.73243930e+161],
        [9.52750676e-130, 2.59027910e-144, 9.29650336e+242]],

       [[3.99003158e+169, 4.30627093e-096, 1.04917763e-153],
        [9.42059416e-143, 9.95513253e-143, 5.81469530e+175],
        [6.21042391e+175, 4.31626845e-096, 2.64986853e+180],
        ...,
        [1.05118842e-153, 3.00948060e-067,

### **Problem 5: Mini-batch Weight Gradients**

A layer has **128 weights**, and gradients are computed for **16 mini-batches** before aggregation.

**Task:**
Create a NumPy array using `np.empty()` to store these gradients.


In [24]:
x = np.empty((16,128))
x

array([[6.79396556e-312, 6.79449360e-312, 6.79398917e-312, ...,
        6.79398917e-312, 6.79622421e-312, 6.79398917e-312],
       [6.79622416e-312, 6.79398917e-312, 6.79622418e-312, ...,
        6.79398917e-312, 6.79622400e-312, 6.79398917e-312],
       [6.79622400e-312, 6.79398917e-312, 6.79622400e-312, ...,
        6.79398917e-312, 6.79622256e-312, 6.79398917e-312],
       ...,
       [6.79621812e-312, 6.79398917e-312, 6.79621813e-312, ...,
        6.79398917e-312, 6.79621811e-312, 6.79398917e-312],
       [6.79621809e-312, 6.79398917e-312, 6.79621811e-312, ...,
        6.79396556e-312, 6.79398917e-312, 6.79396556e-312],
       [6.79621771e-312, 6.79398917e-312, 6.79621773e-312, ...,
        6.79618755e-312, 6.79618755e-312, 6.79618755e-312]],
      shape=(16, 128))