# 5. np.arange()

Creates values in a range, similar to range() but returns an array.

In [1]:
import numpy as np

In [6]:
x = np.arange(1,11)

In [7]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x.shape

(10,)

In [17]:
x = np.arange(0, 10, 2)
x

array([0, 2, 4, 6, 8])

### **Problem 1: Epoch Counter**

You train a model for **50 epochs** and want an array that stores the **epoch numbers starting from 0**.

**Task:**
Create the array using `np.arange()`.


In [18]:
x = np.arange(0,50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### **Problem 2: Sample Indexing**

You have **120 data samples** and need an array of **sample indices starting from 1**.

**Task:**
Create the array using `np.arange()`.


In [19]:
x = np.arange(1,121)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120])

### **Problem 3: Time Steps**

A simulation runs for **10 seconds** with a **time step of 0.5 seconds**, starting from **0**.

**Task:**
Create a NumPy array of time steps using `np.arange()`.


In [20]:
x = np.arange(0,10,0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### **Problem 4: Feature Column IDs**

A dataset has **15 features**, and you want an array of **feature IDs from 0 to 14**.

**Task:**
Create the array using `np.arange()`.


In [21]:
x = np.arange(0,15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### **Problem 5: Even Number Generator**

You need an array of **even numbers from 2 up to (but not including) 40**.

**Task:**
Create the array using `np.arange()`.


In [23]:
x = np.arange(2,40,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])