# 6. np.linspace()

Creates evenly spaced values between two limits.

In [1]:
import numpy as np

In [2]:
x = np.linspace(1,5,10)
x

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [8]:
x = np.linspace(0.01,0.1,10)
x

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])


### **Problem 1: Learning Rate Schedule**

You want **10 evenly spaced learning rate values** between **0.001 and 0.01**, inclusive.

**Task:**
Create the array using `np.linspace()`.


In [10]:
x = np.linspace(0.001,0.01,10)
x

array([0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009,
       0.01 ])

### **Problem 2: Sensor Calibration**

A sensor needs **25 calibration points** between **−5 and 5**, inclusive.

**Task:**
Create the calibration array using `np.linspace()`.


In [11]:
x = np.linspace(-5,5,25)
x

array([-5.        , -4.58333333, -4.16666667, -3.75      , -3.33333333,
       -2.91666667, -2.5       , -2.08333333, -1.66666667, -1.25      ,
       -0.83333333, -0.41666667,  0.        ,  0.41666667,  0.83333333,
        1.25      ,  1.66666667,  2.08333333,  2.5       ,  2.91666667,
        3.33333333,  3.75      ,  4.16666667,  4.58333333,  5.        ])

### **Problem 3: Time Grid**

You simulate a system from **0 to 2 seconds** and want **100 equally spaced time points**, including both endpoints.

**Task:**
Create the time array using `np.linspace()`.


In [12]:
x = np.linspace(0,2,100)
x

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

### **Problem 4: Image Intensity Ramp**

You want **256 grayscale intensity levels** ranging from **0 to 255**, inclusive.

**Task:**
Create the array using `np.linspace()`.


In [20]:
x = np.linspace(0,255,256)
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

### **Problem 5: Threshold Sweep**

You test a classifier with **15 threshold values** between **0 and 1**, inclusive.

**Task:**
Create the array using `np.linspace()`.

In [22]:
x = np.linspace(0,1,15000)
x

array([0.00000000e+00, 6.66711114e-05, 1.33342223e-04, ...,
       9.99866658e-01, 9.99933329e-01, 1.00000000e+00], shape=(15000,))