# 7. `np.eye()`

Creates an identity matrix.



In [1]:
import numpy as np

In [2]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
x = np.eye(3,dtype=int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### **Problem 1: Identity Matrix Creation**

You are building a linear model that requires an identity matrix for feature preservation.

**Task:**
Create a **5 × 5 identity matrix** using `np.eye()`.


In [5]:
x = np.eye(5,5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### **Problem 2: Regularization Matrix**

While implementing L2 regularization, you need a square matrix that penalizes weights equally.

**Task:**
Create a **4 × 4 identity matrix** and scale it by `0.1` using `np.eye()`.


In [6]:
x = 0.1 * np.eye(4)
x

array([[0.1, 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. ],
       [0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0.1]])

### **Problem 3: One-Hot Encoding**

You have **7 classes** in a classification problem and want a one-hot encoding matrix.

**Task:**
Create a **7 × 7 identity matrix** using `np.eye()` and select the row for class index `3`.


In [7]:
x = 3 * np.eye(7)
x

array([[3., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 3.]])

### **Problem 4: Diagonal Masking**

You want to keep only the diagonal values of a **6 × 6 matrix** and zero out all other elements.

**Task:**
Create a diagonal mask using `np.eye(6)` for element-wise multiplication.


In [8]:
x = np.arange(1,37).reshape(6,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
y = np.eye(6)
y

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [10]:
diagonal = x * y 
diagonal

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  8.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 22.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 29.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 36.]])

### **Problem 5: Numerical Stability**

A covariance matrix is nearly singular and causes errors during inversion.

**Task:**
Add a small value `ε = 1e-5` multiplied by an identity matrix to stabilize it using `np.eye()`.


In [13]:
import numpy as np

# example matrix (6 × 6)
A = np.random.rand(6, 6)

# small stability constant
eps = 1e-5

# add epsilon * identity matrix
A_stable = A + eps * np.eye(6)

A_stable


array([[0.24244574, 0.79009249, 0.72320267, 0.31244481, 0.74572668,
        0.11273544],
       [0.3460726 , 0.44714223, 0.57271673, 0.88418097, 0.20417407,
        0.35348636],
       [0.82452357, 0.51217305, 0.77590795, 0.28874732, 0.68254849,
        0.09166839],
       [0.44339609, 0.32304877, 0.02900103, 0.07212484, 0.16694362,
        0.67310511],
       [0.6391165 , 0.91822975, 0.11772201, 0.22786075, 0.43122814,
        0.89274684],
       [0.09897977, 0.72658527, 0.15573764, 0.9654274 , 0.95751282,
        0.46737788]])